config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations, :controllers => {
    omniauth_callbacks: "omniauth_callbacks",
    passwords: "passwords",
    confirmations: "confirmations",
    sessions: "sessions"
  }

  devise_scope :user do
    resource :registration,
      only: [:new, :create],
      path: 'users',
      controller: 'registrations',
      as: :user_registration
  end

  get "users/edit_profile" => "users#edit_profile", as: :edit_profile
  post "users/update_profile" => "users#update_profile", as: :update_profile
  post "users/:id/add_user_role" => "users#add_user_role", as: :add_user_role
  post "users/:id/remove_user_role" => "users#remove_user_role", as: :remove_user_role

  resources :users, only: [:index, :show, :destroy] do
    collection do
      get 'inactive'
    end
  end

  resources :courses do
    member do
      get 'edit_structure'
      post 'set_main'
      post 'unset_main'
    end
  end

  resources :sections do
    member do
      post 'move_down'
      post 'move_up'
    end
  end

  resources :lessons do
    member do
      post 'move_down'
      post 'move_up'
      post 'attach_task'
      post 'detach_task'
      post 'attach_quiz'
      post 'detach_quiz'
    end
  end

  resources :classrooms do
    member do
      get 'lesson/:lesson_id' => 'classrooms#lesson', as: :lesson
      get 'lesson/:lesson_id/task/:task_id' => 'classrooms#lesson_task', as: :lesson_task
      get 'lesson/:lesson_id/task/:task_id/solution' => 'classrooms#task_solution', as: :task_solution
      get 'lesson/:lesson_id/task/:task_id/successful_runs' => 'classrooms#task_successful_runs', as: :task_successful_runs
      get 'lesson/:lesson_id/task/:task_id/task_runs' => 'classrooms#task_runs', as: :task_runs
      get 'lesson/:lesson_id/task/:task_id/task_run/:task_run_id' => 'classrooms#task_run', as: :task_run
      get 'lesson/:lesson_id/task/:task_id/student_task_runs' => 'classrooms#student_task_runs', as: :student_task_runs
      post 'lesson/:lesson_id/task/:task_id/solve' => 'classrooms#solve_task', as: :solve_task

      get 'lesson/:lesson_id/quiz/:quiz_id' => 'classrooms#lesson_quiz', as: :lesson_quiz
      get 'lesson/:lesson_id/quiz/:quiz_id/attempt' => 'classrooms#attempt_quiz', as: :attempt_quiz
      get 'lesson/:lesson_id/quiz/:quiz_id/attempt/:quiz_attempt_id' => 'classrooms#show_quiz_attempt', as: :show_quiz_attempt
      get 'lesson/:lesson_id/quiz/:quiz_id/student_quiz_attempts' => 'classrooms#student_quiz_attempts', as: :student_quiz_attempts
      get 'lesson/:lesson_id/quiz/:quiz_id/student_quiz_attempt' => 'classrooms#student_quiz_attempt', as: :student_quiz_attempt
      post 'lesson/:lesson_id/quiz/:quiz_id/submit' => 'classrooms#submit_quiz', as: :submit_quiz

      get 'users'
      get 'progress'
      get 'student_progress'
      post 'enroll'
      post 'remove_user'
      post 'update_user_limit'
      post 'add_waiting'
      post 'activate_user'
    end
  end

  resources :tasks do
    member do
      get 'solve'
      get 'runs'
      get 'runs_limits'
      get 'solution'
      post 'do_solve'
      post 'update_checker'
      post 'update_runs_limit'
      post 'resubmit_run'
    end

    collection do
      get 'all_runs'
      get 'stats'
    end
  end

  resources :quizzes do
    member do
      get 'attempt'
      get 'show_attempt'
      post 'submit'
    end

    collection do
      get 'all_attempts'
    end
  end

  resources :user_invitations, only: [:index, :create, :update, :destroy]

  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'about_codemarathon' => 'pages#about_codemarathon', as: :about_codemarathon

  root 'pages#home'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:google_oauth2, :github, :facebook]

  has_many :classroom_records, dependent: :destroy
  has_many :roles, dependent: :destroy
  has_many :task_records, dependent: :destroy
  has_many :task_runs, dependent: :destroy
  has_many :quiz_attempts

  validates :email, presence: true

  ROLE_ADMIN = :admin
  ROLE_TEACHER = :teacher
  ROLES = [ROLE_ADMIN, ROLE_TEACHER]

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :with_access, -> { where(active: true).where.not(confirmed_at: nil) }
  scope :no_access, -> { where('active = false OR confirmed_at IS NULL') }
  scope :by_name_email, ->(query) { where('email LIKE ? OR name LIKE ?', "%#{ query }%", "%#{ query }%") }
  scope :ordered_by_creation, -> { order(created_at: :desc) }

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  def self.from_omniauth(auth)
    user = where(email: auth.info.email).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      # Mark user as confirmed because there is no point in confirming when
      # authorizing with OAuth
      user.confirmed_at = DateTime.now
      user.save
    end

    user.set_active_field

    user
  end

  def display_name
    name.present? ? name : email
  end

  def display_roles
    roles.map(&:role_type).join(", ")
  end

  def registered_with_email?
    provider.nil?
  end

  def add_role role_type
    roles.find_or_create_by(role_type: role_type)
  end

  def remove_role role_type
    matched_role = roles.where(role_type: role_type)
    matched_role.destroy_all if matched_role.present?
  end

  def has_role? role_type
    roles.where(role_type: role_type).present?
  end

  def is_teacher?
    has_role?(ROLE_TEACHER)
  end

  def set_active_field
    User.transaction do
      update_attributes(active: true) if can_activate_user?
    end
    true
  end

  private

  def can_activate_user?
    use_invitation || Settings.users_limit.nil? ||
      Settings.users_limit == -1 || User.active.count < Settings.users_limit
  end

  def use_invitation
    invitation = UserInvitation.find_by(email: email)

    if invitation.present? && !invitation.used?
      invitation.update_attributes(used: true, used_at: Time.now)
      true
    else
      false
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    handle_authentication("Google", "devise.google_data")
  end

  def github
    handle_authentication("GitHub", "devise.github_data")
  end

protected

  def handle_authentication(kind, session_key)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      # flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => kind
      sign_in_and_redirect @user, event: :authentication
    else
      session[session_key] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin_role, except: [:edit_profile, :update_profile, :set_last_programming_language]

  def index
    @user_query = params[:query]
    if @user_query
      @users = User.with_access.ordered_by_creation.by_name_email(@user_query).page(params[:page]).per(100)
    else
      @users = User.with_access.ordered_by_creation.page(params[:page]).per(100)
    end
    @active_users_count = User.with_access.count
    @inactive_users_count = User.no_access.count
    @user_invitations_count = UserInvitation.count
  end

  def inactive
    @user_query = params[:query]
    if @user_query
      @inactive_users = User.no_access.ordered_by_creation.by_name_email(@user_query).page(params[:page]).per(100)
    else
      @inactive_users = User.no_access.ordered_by_creation.page(params[:page]).per(100)
    end
    @active_users_count = User.with_access.count
    @inactive_users_count = User.no_access.count
    @user_invitations_count = UserInvitation.count
  end

  def show
    @user = User.find(params[:id])

    redirect_to users_path, alert: "Invalid user" if @user.blank?
  end

  def add_user_role
    @user = User.find(params[:id])

    if @user.blank?
      redirect_to users_path, alert: "Invalid user" if @user.blank?
    else
      @user.add_role(params[:role_type])
      redirect_to user_path(@user), notice: "Role #{params[:role_type]} added to user #{@user.email}"
    end
  end

  def remove_user_role
    @user = User.find(params[:id])

    if @user.blank?
      redirect_to users_path, alert: "Invalid user" if @user.blank?
    else
      @user.remove_role(params[:role_type])
      redirect_to user_path(@user), notice: "Role #{params[:role_type]} removed from user #{@user.email}"
    end
  end

  def edit_profile
    @user = current_user
  end

  def update_profile
    if current_user.update_attributes(user_profile_params)
      redirect_to edit_profile_path, notice: "Profile updated successfully"
    else
      redirect_to edit_profile_path, alert: "Failed to update user profile"
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.has_role?(User::ROLE_TEACHER) || @user.has_role?(User::ROLE_ADMIN)
      redirect_to users_path, alert: "You can't delete tacher/admin users!"
    elsif @user == current_user
      redirect_to users_path, alert: "You can't delete yourself!"
    else
      @user.destroy
      redirect_to users_path, notice: "User was deleted!"
    end
  end

  protected

  def user_profile_params
    params.require(:user).permit(:name)
  end
end

app/views/users/_search_users.html.erb
<div class="text-center margin-bottom-small">
  <%= form_tag '', method: :get do %>
    <%= text_field_tag :query, @user_query %>
    <%= submit_tag 'Search' %>
  <% end %>
</div>

app/views/users/_users_list.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= paginate users, theme: 'twitter-bootstrap-3' %>
    <table class="table table-striped table-hover table-condensed" >
      <tr>
        <th>ID</th>
        <th>Email</th>
        <th>Name</th>
        <th>Roles</th>
        <th>Time registered</th>
        <th>Confirmed at</th>
        <th>Auth provider</th>
        <th>Action</th>
      </tr>
      <% users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= link_to user.email, user_path(user) %></td>
          <td title="<%= user.name %>"><%= truncate(user.name, length: 25) %></td>
          <td><%= user.display_roles %></td>
          <td><%= user.created_at.to_s(:db) %></td>
          <td><%= user.confirmed_at.to_s(:db) if user.confirmed_at %></td>
          <td><%= user.provider %></td>
          <% unless user == current_user || user.has_role?(User::ROLE_TEACHER) || user.has_role?(User::ROLE_ADMIN) %>
            <td><%= link_to 'Delete', user, :class => "btn btn-xs btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <%= paginate users, theme: 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/users/_users_top_menu.html.erb
<div class="text-center margin-bottom-small">
  <%= link_to 'Active users', users_path %> <span class="badge"><%= @active_users_count %></span> |
  <%= link_to 'Inactive users', inactive_users_path %> <span class="badge"><%= @inactive_users_count %></span> |
  <%= link_to 'Invitations', user_invitations_path %> <span class="badge"><%= @user_invitations_count %></span> |
  User limit <span class="badge"><%= Settings.users_limit.present? ? Settings.users_limit : 'None' %></span>
</div>

app/views/users/edit_profile.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 text-center border-bottom">
    <h2>Edit profile</h2>
  </div>
</div>

<div class="row main-log-in-panel">
  <%= bootstrap_form_for(@user, url: update_profile_path(@user), html: { method: :post }) do |f| %>

    <div class="form-fields-box col-md-4 col-md-offset-4">
      <div class="text-center"><h4>
        <span class="label label-primary">
          <%= @user.email %>
        </span>
      </h4></div>

      <div class="text-center"><h4>
        <% @user.roles.each do |role| %>
          <span class="label label-success"><%= role.role_type %></span>
        <% end %>
      </h4></div>

      <div class="field">
        <%= f.text_field :name, autocomplete: "off", label: "Name" %>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="col-md-4 col-md-offset-4 margin-top-small">
      <div class="actions text-center">
        <%= f.submit "Update profile", class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>

</div>

app/views/users/inactive.html.erb
<h2 class="text-center">Inactive users</h2>

<%= render partial: 'users_top_menu' %>

<%= render partial: 'search_users' %>

<%= render partial: 'users_list', locals: { users: @inactive_users } %>

app/views/users/index.html.erb
<h2 class="text-center">Users list</h2>

<%= render partial: 'users_top_menu' %>

<%= render partial: 'search_users' %>

<%= render partial: 'users_list', locals: { users: @users } %>

app/views/users/show.html.erb
<h2 class="text-center">Manage user</h2>

<div class="text-center"><h4>
  <span class="label label-primary">
    <%= @user.email %>
  </span>
</h4></div>

<div class="text-center margin-top-small margin-bottom-small border-bottom">
<h5><b>Name:</b> <%= @user.display_name %></h5>
</div>

<div class="row">
  <div class="col-md-2 col-md-offset-2">
    <%= bootstrap_form_tag(url: add_user_role_path(@user), method: :post) do |f| %>
      <div class="field">
        <%= f.select :role_type, User::ROLES, label: nil %>
      </div>
      <div class="field text-center">
        <%= f.submit "Add role", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <% unless @user.roles.empty? %>
    <div class="col-md-2">
      <ul>
        <% @user.roles.each do |role| %>
          <li><%= role.role_type %> <%= link_to 'X', remove_user_role_path(@user, role_type: role.role_type), method: :post %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<div class="row margin-top-average">
  <div class="col-md-8 col-md-offset-2">
    <h4>Classrooms</h4>
    <table class="table">
      <tr>
        <th>Course</th>
        <th>Classroom</th>
        <th>Role</th>
        <th>Active?</th>
      </tr>
      <% @user.classroom_records.each do |record| %>
        <tr>
          <td><%= link_to record.classroom.course.title, course_path(record.classroom.course) %></td>
          <td><%= link_to record.classroom.name, student_progress_classroom_path(record.classroom, user_id: @user.id) %></td>
          <td><%= record.role %></td>
          <td><%= record.active %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>