config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations, :controllers => {
    omniauth_callbacks: "omniauth_callbacks",
    passwords: "passwords",
    confirmations: "confirmations",
    sessions: "sessions"
  }

  devise_scope :user do
    resource :registration,
      only: [:new, :create],
      path: 'users',
      controller: 'registrations',
      as: :user_registration
  end

  get "users/edit_profile" => "users#edit_profile", as: :edit_profile
  post "users/update_profile" => "users#update_profile", as: :update_profile
  post "users/:id/add_user_role" => "users#add_user_role", as: :add_user_role
  post "users/:id/remove_user_role" => "users#remove_user_role", as: :remove_user_role

  resources :users, only: [:index, :show, :destroy] do
    collection do
      get 'inactive'
    end
  end

  resources :courses do
    member do
      get 'edit_structure'
      post 'set_main'
      post 'unset_main'
    end
  end

  resources :sections do
    member do
      post 'move_down'
      post 'move_up'
    end
  end

  resources :lessons do
    member do
      post 'move_down'
      post 'move_up'
      post 'attach_task'
      post 'detach_task'
      post 'attach_quiz'
      post 'detach_quiz'
    end
  end

  resources :classrooms do
    member do
      get 'lesson/:lesson_id' => 'classrooms#lesson', as: :lesson
      get 'lesson/:lesson_id/task/:task_id' => 'classrooms#lesson_task', as: :lesson_task
      get 'lesson/:lesson_id/task/:task_id/solution' => 'classrooms#task_solution', as: :task_solution
      get 'lesson/:lesson_id/task/:task_id/successful_runs' => 'classrooms#task_successful_runs', as: :task_successful_runs
      get 'lesson/:lesson_id/task/:task_id/task_runs' => 'classrooms#task_runs', as: :task_runs
      get 'lesson/:lesson_id/task/:task_id/task_run/:task_run_id' => 'classrooms#task_run', as: :task_run
      get 'lesson/:lesson_id/task/:task_id/student_task_runs' => 'classrooms#student_task_runs', as: :student_task_runs
      post 'lesson/:lesson_id/task/:task_id/solve' => 'classrooms#solve_task', as: :solve_task

      get 'lesson/:lesson_id/quiz/:quiz_id' => 'classrooms#lesson_quiz', as: :lesson_quiz
      get 'lesson/:lesson_id/quiz/:quiz_id/attempt' => 'classrooms#attempt_quiz', as: :attempt_quiz
      get 'lesson/:lesson_id/quiz/:quiz_id/attempt/:quiz_attempt_id' => 'classrooms#show_quiz_attempt', as: :show_quiz_attempt
      get 'lesson/:lesson_id/quiz/:quiz_id/student_quiz_attempts' => 'classrooms#student_quiz_attempts', as: :student_quiz_attempts
      get 'lesson/:lesson_id/quiz/:quiz_id/student_quiz_attempt' => 'classrooms#student_quiz_attempt', as: :student_quiz_attempt
      post 'lesson/:lesson_id/quiz/:quiz_id/submit' => 'classrooms#submit_quiz', as: :submit_quiz

      get 'users'
      get 'progress'
      get 'student_progress'
      post 'enroll'
      post 'remove_user'
      post 'update_user_limit'
      post 'add_waiting'
      post 'activate_user'
    end
  end

  resources :tasks do
    member do
      get 'solve'
      get 'runs'
      get 'runs_limits'
      get 'solution'
      post 'do_solve'
      post 'update_checker'
      post 'update_runs_limit'
      post 'resubmit_run'
    end

    collection do
      get 'all_runs'
      get 'stats'
    end
  end

  resources :quizzes do
    member do
      get 'attempt'
      get 'show_attempt'
      post 'submit'
    end

    collection do
      get 'all_attempts'
    end
  end

  resources :user_invitations, only: [:index, :create, :update, :destroy]

  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'about_codemarathon' => 'pages#about_codemarathon', as: :about_codemarathon

  root 'pages#home'

end

app/models/lesson.rb
# TODO: Extract all the common logic with sections and do the same for specs.
class Lesson < ApplicationRecord
  before_save :render_markdown_content

  belongs_to :section
  has_many :lesson_records, dependent: :destroy
  has_and_belongs_to_many :tasks
  has_and_belongs_to_many :quizzes

  validates :title, presence: true
  validates :position, presence: true
  validates :section, presence: true
  validates :visible, inclusion: { in: [true, false] }

  scope :ordered, -> { order('position ASC') }
  scope :visible, -> { where(visible: true) }

  def is_first?
    section.lessons.ordered.first.id == id
  end

  def is_last?
    section.lessons.ordered.last.id == id
  end

  def previous_visible_lesson_in_course admin_user: false
    curr_lesson = previous_lesson
    while curr_lesson.present? && !admin_user && !curr_lesson.visible
      curr_lesson = curr_lesson.previous_lesson
    end

    curr_lesson
  end

  def next_visible_lesson_in_course admin_user: false
    curr_lesson = next_lesson
    while curr_lesson.present? && !admin_user && !curr_lesson.visible
      curr_lesson = curr_lesson.next_lesson
    end

    curr_lesson
  end

  def move_up
    return if is_first?

    Lesson.transaction do
      new_positon = previous_lesson.position

      previous_lesson.update_attributes(position: position)
      update_attributes(position: new_positon)
    end
  end

  def move_down
    return if is_last?

    Lesson.transaction do
      new_positon = next_lesson.position

      next_lesson.update_attributes(position: position)
      update_attributes(position: new_positon)
    end
  end

  def lesson_record_for(classroom, user)
    lesson_records.find_or_create_by(classroom: classroom, user: user) if user.present?
  end

  def all_tasks_covered_by?(user)
    if user.present?
      tasks.map { |task| task.is_covered_by?(user) }.all?
    else
      tasks.empty?
    end
  end

  def all_quizzes_covered_by?(user)
    if user.present?
      quizzes.map { |quiz| quiz.is_covered_by?(user) }.all?
    else
      quizzes.empty?
    end
  end

  def count_covered_tasks_by(user)
    if user.present?
      tasks.to_a.count { |task| task.is_covered_by?(user) }
    else
      0
    end
  end

  def marked_covered?(classroom, user)
    user.present? && lesson_record_for(classroom, user).covered
  end

  def cover_lesson_records_if_lesson_covered(user)
    if is_covered?(user)
      lesson_records.where(user: user).each do |lesson_record|
        lesson_record.update_attributes(covered: true) if lesson_record.views > 0
      end
    end
  end

  def is_covered?(user)
    all_tasks_covered_by?(user) && all_quizzes_covered_by?(user)
  end

  def section_quizzes
    section.lessons.each do |lesson|
      lesson.quizzes.each do |quiz|
        yield lesson, quiz
      end
    end
  end

  def section_tasks
    section.lessons.each do |lesson|
      lesson.tasks.each do |task|
        yield lesson, task
      end
    end
  end

  protected

  def previous_lesson
    unless is_first?
      section.lessons.find_by(position: position - 1)
    else
      prev_section = section.previous_section
      while prev_section.present? && prev_section.lessons.empty?
        prev_section = prev_section.previous_section
      end
      return if prev_section.nil?
      prev_section.lessons.ordered.last
    end
  end

  def next_lesson
    unless is_last?
      section.lessons.find_by(position: position + 1)
    else
      next_section = section.next_section
      while next_section.present? && next_section.lessons.empty?
        next_section = next_section.next_section
      end
      return if next_section.nil?
      next_section.lessons.ordered.first
    end
  end

  def render_markdown_content
    if markdown_content.present?
      self.content = RenderMarkdown.new(markdown_content).call
    end

    if markdown_sidebar_content.present?
      self.sidebar_content = RenderMarkdown.new(markdown_sidebar_content).call
    end
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_teacher_role

  def create
    section = Section.find(lesson_params[:section_id])

    if Lesson.create!(lesson_params.merge(position: section.last_lesson_position + 1))
      redirect_to edit_structure_course_path(section.course), notice: "Lesson created successfully"
    else
      redirect_to edit_structure_course_path(section.course), alert: "Failed to create new lesson"
    end
  end

  def edit
    lesson
  end

  def update
    if lesson.update_attributes(lesson_params)
      flash[:notice] = "Course updated successfully"
      render 'edit'
    else
      flash[:alert] = "Failed to update course contents"
      render 'edit'
    end
  end

  def destroy
    lesson.destroy

    redirect_to edit_structure_course_path(course), notice: "Lesson deleted"
  end

  def move_up
    lesson.move_up

    redirect_to edit_structure_course_path(course)
  end

  def move_down
    lesson.move_down

    redirect_to edit_structure_course_path(course)
  end

  def attach_task
    if lesson.tasks.map(&:id).include?(params[:task_id])
      redirect_to edit_lesson_path(lesson), alert: "Task already attached to lesson"
    else
      lesson.tasks << Task.find(params[:task_id])
      redirect_to edit_lesson_path(lesson), notice: "Task attached to lesson successfully"
    end
  end

  def detach_task
    lesson.tasks.delete(Task.find(params[:task_id]))
    redirect_to edit_lesson_path(lesson), notice: "Task detached from lesson successfully"
  end

  def attach_quiz
    if lesson.quizzes.map(&:id).include?(params[:quiz_id])
      redirect_to edit_lesson_path(lesson), alert: "Quiz already attached to lesson"
    else
      lesson.quizzes << Quiz.find(params[:quiz_id])
      redirect_to edit_lesson_path(lesson), notice: "Quiz attached to lesson successfully"
    end
  end

  def detach_quiz
    lesson.quizzes.delete(Quiz.find(params[:quiz_id]))
    redirect_to edit_lesson_path(lesson), notice: "Quiz detached from lesson successfully"
  end

  protected

  def lesson
    @lesson ||= Lesson.find(params[:id])
  end

  def course
    lesson.section.course
  end

  def lesson_params
    params.require(:lesson).permit(:title, :section_id, :markdown_content,
      :markdown_sidebar_content, :visible)
  end
end

app/views/lessons/_attach_quizzes.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Attached quizzes to lesson
      </div>

      <div class="panel-body">
        <% if lesson.quizzes.present? %>
          <ul class="list-group">
            <% lesson.quizzes.each do |quiz| %>
              <li class="list-group-item">
                <%= link_to quiz.title, quiz_path(quiz) %>
                <%= link_to "Detach", detach_quiz_lesson_path(lesson, quiz_id: quiz.id), method: :post, class: 'btn btn-danger btn-xs pull-right' %>
              </li>
            <% end %>
          </ul>
        <% else %>
          No quizzes in lesson
        <% end %>
      </div>

      <div class="panel-footer text-center">
        <% if Quiz.unused_quizzes_for(lesson).present? %>
          <%= form_tag(attach_quiz_lesson_path(lesson), method: :post) do %>
            <%= select_tag :quiz_id, options_from_collection_for_select(Quiz.unused_quizzes_for(lesson), "id", "title") %>
            <%= submit_tag "Attach quiz", class: "btn btn-primary btn-sm" %>
          <% end %>
        <% else %>
          All existing quizzes are attached to this lesson
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lessons/_attach_tasks.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Attached tasks to lesson
      </div>

      <div class="panel-body">
        <% if lesson.tasks.present? %>
          <ul class="list-group">
            <% lesson.tasks.each do |task| %>
              <li class="list-group-item">
                <%= link_to task.title, task_path(task) %>
                <%= link_to "Detach", detach_task_lesson_path(lesson, task_id: task.id), method: :post, class: 'btn btn-danger btn-xs pull-right' %>
              </li>
            <% end %>
          </ul>
        <% else %>
          No tasks in lesson
        <% end %>
      </div>

      <div class="panel-footer text-center">
        <% if Task.unused_tasks_for(lesson).present? %>
          <%= form_tag(attach_task_lesson_path(lesson), method: :post) do %>
            <%= select_tag :task_id, options_from_collection_for_select(Task.unused_tasks_for(lesson), "id", "title") %>
            <%= submit_tag "Attach task", class: "btn btn-primary btn-sm" %>
          <% end %>
        <% else %>
          All existing tasks are attached to this lesson
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lessons/_change_position.html.erb
<td class="col-md-1">
  <% unless lesson.is_first? %>
    <%= button_to  move_up_lesson_path(lesson), method: :post, class: 'btn btn-sm btn-primary' do %>
      <span class="glyphicon glyphicon-arrow-up"></span>
    <% end %>
  <% end %>
</td>

<td class="col-md-1">
  <% unless lesson.is_last? %>
    <%= button_to move_down_lesson_path(lesson), method: :post, class: 'btn btn-sm btn-primary' do %>
      <span class="glyphicon glyphicon-arrow-down"></span>
    <% end %>
  <% end %>
</td>

app/views/lessons/_edit_title.html.erb
<%= bootstrap_form_for(lesson, layout: :inline) do |f| %>
  <%= f.text_field :title, hide_label: true, class: "long-field input-sm" %>
  <%= f.submit "Update", class: "btn btn-sm btn-primary" %>
<% end %>

app/views/lessons/_new.html.erb
<div class="modal fade" id=<%= "new-lesson-modal-#{ section.id }" %> tabindex="-1" role="dialog" aria-labelledby="new-lesson-modal-label">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="new-lesson-modal-label">Create new lesson in section "<%= section.title %>"</h4>
      </div>
      <%= bootstrap_form_for(Lesson.new) do |f| %>
        <div class="modal-body">
            <div class="row col-md-8 col-md-offset-2">
              <%= f.text_field :title, class: "input-lg", placeholder: "New lesson title", hide_label: true %>
              <%= f.hidden_field :section_id, value: section.id %>
            </div>
          <div class="clearfix"></div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Create lesson", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/lessons/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2 text-center">
    <h5><%= link_to 'Back to course structure', edit_structure_course_path(@lesson.section.course) %></h5>
    <h2>Edit lesson "<%= @lesson.title %>"</h2>
  </div>
</div>

<%= render partial: 'attach_tasks', locals: { lesson: @lesson } %>
<%= render partial: 'attach_quizzes', locals: { lesson: @lesson } %>

<%= bootstrap_form_for(@lesson) do |f| %>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.text_area :markdown_content, rows: 20, label: "Lesson contents via markdown (preview doesn't support code blocks and tables)", "data-provide" => "markdown", placeholder: "Content of lesson" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.text_area :markdown_sidebar_content, rows: 20, label: "Lesson sidebar contents via markdown (preview doesn't support code blocks and tables)", "data-provide" => "markdown", placeholder: "Sidebar content of lesson" %>
    </div>
  </div>

  <div class="row text-center">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Cancel", edit_structure_course_path(@lesson.section.course), class: "btn btn-default" %>
  </div>
<% end %>