config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations, :controllers => {
    omniauth_callbacks: "omniauth_callbacks",
    passwords: "passwords",
    confirmations: "confirmations",
    sessions: "sessions"
  }

  devise_scope :user do
    resource :registration,
      only: [:new, :create],
      path: 'users',
      controller: 'registrations',
      as: :user_registration
  end

  get "users/edit_profile" => "users#edit_profile", as: :edit_profile
  post "users/update_profile" => "users#update_profile", as: :update_profile
  post "users/:id/add_user_role" => "users#add_user_role", as: :add_user_role
  post "users/:id/remove_user_role" => "users#remove_user_role", as: :remove_user_role

  resources :users, only: [:index, :show, :destroy] do
    collection do
      get 'inactive'
    end
  end

  resources :courses do
    member do
      get 'edit_structure'
      post 'set_main'
      post 'unset_main'
    end
  end

  resources :sections do
    member do
      post 'move_down'
      post 'move_up'
    end
  end

  resources :lessons do
    member do
      post 'move_down'
      post 'move_up'
      post 'attach_task'
      post 'detach_task'
      post 'attach_quiz'
      post 'detach_quiz'
    end
  end

  resources :classrooms do
    member do
      get 'lesson/:lesson_id' => 'classrooms#lesson', as: :lesson
      get 'lesson/:lesson_id/task/:task_id' => 'classrooms#lesson_task', as: :lesson_task
      get 'lesson/:lesson_id/task/:task_id/solution' => 'classrooms#task_solution', as: :task_solution
      get 'lesson/:lesson_id/task/:task_id/successful_runs' => 'classrooms#task_successful_runs', as: :task_successful_runs
      get 'lesson/:lesson_id/task/:task_id/task_runs' => 'classrooms#task_runs', as: :task_runs
      get 'lesson/:lesson_id/task/:task_id/task_run/:task_run_id' => 'classrooms#task_run', as: :task_run
      get 'lesson/:lesson_id/task/:task_id/student_task_runs' => 'classrooms#student_task_runs', as: :student_task_runs
      post 'lesson/:lesson_id/task/:task_id/solve' => 'classrooms#solve_task', as: :solve_task

      get 'lesson/:lesson_id/quiz/:quiz_id' => 'classrooms#lesson_quiz', as: :lesson_quiz
      get 'lesson/:lesson_id/quiz/:quiz_id/attempt' => 'classrooms#attempt_quiz', as: :attempt_quiz
      get 'lesson/:lesson_id/quiz/:quiz_id/attempt/:quiz_attempt_id' => 'classrooms#show_quiz_attempt', as: :show_quiz_attempt
      get 'lesson/:lesson_id/quiz/:quiz_id/student_quiz_attempts' => 'classrooms#student_quiz_attempts', as: :student_quiz_attempts
      get 'lesson/:lesson_id/quiz/:quiz_id/student_quiz_attempt' => 'classrooms#student_quiz_attempt', as: :student_quiz_attempt
      post 'lesson/:lesson_id/quiz/:quiz_id/submit' => 'classrooms#submit_quiz', as: :submit_quiz

      get 'users'
      get 'progress'
      get 'student_progress'
      post 'enroll'
      post 'remove_user'
      post 'update_user_limit'
      post 'add_waiting'
      post 'activate_user'
    end
  end

  resources :tasks do
    member do
      get 'solve'
      get 'runs'
      get 'runs_limits'
      get 'solution'
      post 'do_solve'
      post 'update_checker'
      post 'update_runs_limit'
      post 'resubmit_run'
    end

    collection do
      get 'all_runs'
      get 'stats'
    end
  end

  resources :quizzes do
    member do
      get 'attempt'
      get 'show_attempt'
      post 'submit'
    end

    collection do
      get 'all_attempts'
    end
  end

  resources :user_invitations, only: [:index, :create, :update, :destroy]

  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'about_codemarathon' => 'pages#about_codemarathon', as: :about_codemarathon

  root 'pages#home'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_teacher_role, except: [:index, :show]

  def index
    if user_signed_in?
      @admin_courses = current_user.classroom_records.admin.map { |record| record.classroom.course }.uniq
      @student_courses = current_user.classroom_records.student.map { |record| record.classroom.course }.uniq
      @other_courses = Course.visible_for(current_user) - @admin_courses - @student_courses
    else
      @admin_courses = @student_courses = []
      @other_courses = Course.all.visible
    end
  end

  def show
    course
    @wide_page = true
    if course.classrooms.present?
      @first_lesson = @course.classrooms.first.first_lesson(current_user)
    else
      @first_lesson = nil
    end
    unless course.visible || (user_signed_in? && current_user.is_teacher?)
      redirect_to root_path
    end
    store_location_for(:user, course_path(course))
  end

  def new
    @course = Course.new
  end

  def create
    @course = CreateCourse.new(course_params, current_user).call

    if @course.present?
      redirect_to course_path(@course), notice: "Course created successfully"
    else
      redirect_to new_course_path, alert: "Failed to create new course. #{ course.errors.full_messages }"
    end
  end

  def edit
    course
  end

  def update
    if course.update_attributes(course_params)
      redirect_to edit_course_path(course), notice: "Course updated successfully"
    else
      redirect_to edit_course_path(course), alert: "Failed to update course contents. #{ course.errors.full_messages }"
    end
  end

  def destroy
    course.destroy

    redirect_to root_path, notice: "Course was deleted successfully"
  end

  def edit_structure
    course
  end

  def set_main
    if course.present?
      main_course = Course.main.first
      if main_course != course
        main_course.update_attributes(is_main: false) if main_course.present?
        course.update_attributes(is_main: true)
      end
      redirect_to edit_course_path(course), notice: "New main course set"
    else
      redirect_to root_path, alert: "No matching course found"
    end
  end

  def unset_main
    if course.present?
      course.update_attributes(is_main: false)
      redirect_to edit_course_path(course), notice: "Course is not main anymore"
    else
      redirect_to root_path, alert: "No matching course found"
    end
  end

  protected

  def course
    @course ||= Course.find_by(slug: params[:id])
    raise ActiveRecord::RecordNotFound if @course.nil?
    @course
  end

  def course_params
    params.require(:course).permit(:title, :subtitle, :slug, :markdown_description,
      :markdown_long_description, :visible, :public, :disable_task_submissions)
  end
end

app/views/courses/_course.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= link_to course.title, course_path(course) %></div>
  <div class="panel-body">
    <%= render inline: course.description %>
  </div>
  <% if user_signed_in? && current_user.is_teacher? %>
    <div class="panel-footer">
      <%= link_to 'Edit', edit_course_path(course) %>
      |
      <%= link_to 'Delete', course_path(course), method: :delete, data: { confirm: "Are you sure you want to delete the course '#{course.title}'?" } %>
      <span class="pull-right glyphicon glyphicon-eye-<%= course.visible ? 'open' : 'close' %>" aria-hidden="true"></span>
      <% if course.is_main %>
        <span class="pull-right margin-right-small glyphicon glyphicon-certificate" aria-hidden="true" title="Main course"></span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/courses/_course_call_to_action.html.erb
<div class="call-to-action">
  <% if user_signed_in? %>
    <% if classroom.has_access?(current_user) %>
      <% if classroom.first_lesson(current_user).present? %>
        <%= link_to 'Go to classroom', lesson_classroom_path(classroom, lesson_id: classroom.first_lesson(current_user)), class: "btn btn-lg btn-primary" %>
      <% else %>
        <%= link_to 'Go to classroom', classroom_path(classroom), class: "btn btn-lg btn-primary" %>
      <% end %>
    <% elsif classroom.spots_left > 0 %>
      <%= link_to 'Enroll in classroom', enroll_classroom_path(classroom), method: :post, class: "btn btn-lg btn-success" %>
    <% elsif classroom.is_waiting?(current_user) %>
      <div class="alert alert-success small-alert">
        You are on the waiting list for this classroom.
      </div>
    <% else %>
      <%= link_to 'Sign up to the waiting list', add_waiting_classroom_path(classroom), method: :post, class: "btn btn-lg btn-primary" %>
    <% end %>
  <% else %>
    <% if classroom.spots_left > 0 %>
      <%= link_to 'Log in to enroll in classroom', new_user_session_path, class: "btn btn-lg btn-primary" %>
    <% else %>
      <%= link_to 'Sign up to the waiting list', new_user_session_path, class: "btn btn-lg btn-primary" %>
    <% end %>
  <% end %>

  <% if classroom.user_limit.present? && !classroom.has_access?(current_user) %>
      <% if classroom.spots_left > 0 && classroom.spots_left < Float::INFINITY %>
        <div class="cta-explanation margin-top-tiny spots-left">
          <%= pluralize(classroom.spots_left, "spot") %> left in classroom
        </p>
      <% elsif classroom.user_limit == 0 %>
        <div class="cta-explanation margin-top-tiny course-under-dev">
          This course is currently under development. When you are on the waiting list you'll get enrolled automatically when this happens.
        </p>
      <% elsif classroom.spots_left == 0 %>
        <div class="cta-explanation margin-top-tiny no-free-spots">
          All spots in this course are currently taken. More will open up soon. When you are on the waiting list you'll get enrolled automatically when this happens.
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/courses/_edit_visibility.html.erb
<%= form_for(course_item, layout: :inline) do |f| %>
  <%= f.hidden_field :visible, value: !course_item.visible %>
  <%= button_tag class: "btn btn-sm btn-#{ course_item.visible ? 'primary' : 'default' }" do %>
    <span class="glyphicon glyphicon-eye-<%= course_item.visible ? 'open' : 'close' %>"></span>
  <% end %>
<% end %>

app/views/courses/_fields.html.erb
<%= bootstrap_form_for(@course) do |f| %>
  <div class="row">
    <div class="text-center col-sm-8 col-sm-offset-2">
      <%= f.check_box :visible %>
      <%= f.check_box :public %>
      <%= f.check_box :disable_task_submissions %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.text_field :title, class: "input-lg", placeholder: "Course title", required: true %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.text_field :subtitle, class: "input-lg", placeholder: "Course subtitle (optional)" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.text_field :slug, class: "input-lg", placeholder: "Slug used in URLs", required: true %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.text_area :markdown_description, rows: 6, label: "Description for main page panel via markdown (preview doesn't support code blocks and tables)", "data-provide" => "markdown", placeholder: "Short description, which will show on the courses list", required: true %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.text_area :markdown_long_description, rows: 20, label: "Long description via markdown (preview doesn't support code blocks and tables)", "data-provide" => "markdown", placeholder: "Longer course description, which will show on the main course page", required: true %>
    </div>
  </div>

  <div class="row text-center">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/courses/_menu.html.erb
<ul class="course-menu">
  <% course.sections_visible_for(current_user).ordered.each do |section| %>
    <li class="course-menu-section"><%= section.title %></li>
    <% section.lessons_visible_for(current_user).ordered.each do |lesson| %>
      <li class="course-menu-lesson <%= 'active' if current_lesson.present? && current_lesson.id == lesson.id %>">
        <%= link_to lesson_classroom_path(@classroom, lesson_id: lesson.id) do %>
          <span class="glyphicon glyphicon-<%= lesson.tasks.present? ? 'tasks' : 'book' %> <%= 'green' if lesson.marked_covered?(@classroom, current_user) %>"></span> <%= lesson.title %>
            <% if lesson.tasks.present? %>
              <% if current_user %>
                <span class="badge"><%= "#{ lesson.count_covered_tasks_by(current_user) } / #{ lesson.tasks.count }" %></span>
              <% else %>
                <span class="badge"><%= "#{ lesson.tasks.count }" %></span>
              <% end %>
            <% end %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/courses/_menu_new.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <% course.sections_visible_for(current_user).ordered.each do |section| %>
        <li class="section">
          <%= link_to '#' do %>
            <i class="fa fa-folder fa-fw"></i> <%= section.title %><span class="fa arrow"></span>
          <% end %>
          <ul class="nav nav-second-level">
            <% section.lessons_visible_for(current_user).ordered.each do |lesson| %>
              <li class="lesson">
                <%= link_to lesson_classroom_path(@classroom, lesson_id: lesson.id), class: "lesson-link-#{ lesson.id }" do %>
                  <i class="glyphicon glyphicon-<%= lesson_menu_icon(lesson) %> <%= 'green' if lesson.marked_covered?(@classroom, current_user) %>"></i> <%= lesson.title %>
                    <% if lesson.tasks.present? %>
                      <% if current_user %>
                        <span class="badge"><%= "#{ lesson.count_covered_tasks_by(current_user) } / #{ lesson.tasks.count }" %></span>
                      <% else %>
                        <span class="badge"><%= "#{ lesson.tasks.count }" %></span>
                      <% end %>
                    <% end %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/courses/edit.html.erb
<div class="row text-center">
  <div class="col-md-8 col-md-offset-2">
    <h5><%= link_to @course.title, course_path(@course) %></h5>
    <h2>Edit course details</h2>
  </div>
</div>

<div class="text-center with-margin">
  <%= link_to 'Edit course structure', edit_structure_course_path(@course), class: 'btn btn-primary' %>
  <% if @course.is_main %>
    <%= link_to 'Unset main', unset_main_course_path(@course), class: 'btn btn-primary', method: :post %>
  <% else %>
    <%= link_to 'Set main', set_main_course_path(@course), class: 'btn btn-primary', method: :post %>
  <% end %>
</div>

<%= render partial: 'fields' %>

app/views/courses/edit_structure.html.erb
<div class="row text-center">
  <div class="col-md-8 col-md-offset-2">
    <h5><%= link_to @course.title, course_path(@course) %></h5>
    <h2>Edit course structure</h2>
  </div>
</div>

<%= render partial: 'sections/new', locals: { course: @course } %>

<div class="text-center with-margin">
  <%= link_to 'Edit course main page', edit_course_path(@course), class: 'btn btn-primary' %>
  <button type="button" class="btn btn-success" data-toggle="modal" data-target="#new-section-modal">
    Create new section
  </button>
</div>

<div class="col-md-10 col-md-offset-1">
  <table class="table margin-bottom-large">
    <% @course.sections.ordered.each do |section| %>
      <tr class="section">
        <td class="col-md-7"><%= render partial: 'sections/edit_title', locals: { section: section } %></td>

        <td class="col-md-1">
          <%= render partial: 'courses/edit_visibility', locals: { course_item: section } %>
        </td>

        <td class="col-md-1">
          <%= render partial: 'lessons/new', locals: { section: section } %>

          <button type="button" class="btn btn-sm btn-success" title="New lesson" data-toggle="modal" data-target=<%= "#new-lesson-modal-#{ section.id }" %> >
            <span class="glyphicon glyphicon-new-window">
          </button>
        </td>

        <%= render partial: 'sections/change_position', locals: { section: section } %>

        <td class="col-md-1">
          <%= link_to section_path(section), method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "Are you sure you want to delete section \"#{ section.title }\"?" } do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>

      </tr>
      <% section.lessons.ordered.each do |lesson| %>
        <tr class="lesson">
          <td class="title col-md-7">
            <%= render partial: 'lessons/edit_title', locals: { lesson: lesson } %>
          </td>

          <td class="col-md-1">
            <%= render partial: 'courses/edit_visibility', locals: { course_item: lesson } %>
          </td>

          <td class="col-md-1">
            <%= link_to edit_lesson_path(lesson), class: "btn btn-sm btn-warning", title: "Edit" do %>
              <span class="glyphicon glyphicon-edit"></span>
            <% end %>
          </td>
          <%= render partial: 'lessons/change_position', locals: { lesson: lesson } %>

          <td class="col-md-1">
            <%= link_to lesson_path(lesson), method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "Are you sure you want to delete lesson \"#{ lesson.title }\"?" } do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>

        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/courses/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% unless @admin_courses.empty? && @student_courses.empty? && @other_courses.empty? %>
      <% unless @admin_courses.empty? %>
        <div class="course-group">
          <h4><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Courses where you are an admin</h4>
          <%= render @admin_courses %>
        </div>
      <% end %>
      <% unless @student_courses.empty? %>
        <div class="course-group">
          <h4><span class="glyphicon glyphicon-bookmark"></span>&nbsp;&nbsp;Your current courses</h4>
          <%= render @student_courses %>
        </div>
      <% end %>
      <% unless @other_courses.empty? %>
        <div class="course-group">
          <h4>
            <span class="glyphicon glyphicon-th"></span>&nbsp;&nbsp;
            <% if @admin_courses.empty? && @student_courses.empty? %>
              Available courses
            <% else %>
              More available courses
            <% end %>
          </h4>
          <%= render @other_courses %>
        </div>
      <% end %>
    <% else %>
      <div class="text-center">No courses are available at this time</div>
    <% end %>
  </div>
</div>

app/views/courses/new.html.erb
<div class="row text-center">
  <div class="col-md-8 col-md-offset-2">
    <h2>Start a new course</h2>
  </div>
</div>

<%= render partial: 'fields' %>

app/views/courses/show.html.erb
<div class="course-page">
  <div class="course-title">
    <h2 class="text-center"><%= @course.title %></h2>
    <% if @course.subtitle.present? %>
      <h3 class="text-center"><%= @course.subtitle %></h3>
    <% end %>
  </div>

  <div class="course-description">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
        <%= render inline: @course.long_description %>
      </div>
      <div class="col-md-4">
        <div class="course-summary">
          <strong>COURSE SYLLABUS</strong>
          <table class="course-sylabus">
            <% @course.sections.visible.ordered.each do |section| %>
              <tr>
                <td class="section-arrow">
                  <span class="glyphicon glyphicon-play"></span>
                </td>
                <td class="section-title">
                  <%= section.title %>
                </td>
                <td class="section-stat text-center">
                  <span class="label label-primary" data-toggle="tooltip" data-placement="left" title="lessons">
                    <%= section.lessons.visible.count %> <i class="glyphicon glyphicon-book"></i>
                  </span>
                </td>
                <% unless @course.tasks.empty? %>
                  <td class="section-stat text-center">
                    <span class="label label-success" data-toggle="tooltip" data-placement="right" title="tasks">
                      <%= section.visible_tasks_count %> <i class="glyphicon glyphicon-tasks"></i>
                    </span>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">
        <%= render partial: 'course_call_to_action', locals: { course: @course, classroom: @course.classrooms.first } %>
        <% unless (current_user && @course.classrooms.first.has_access?(current_user)) || !@course.public? %>
          <hr>
          <% if @first_lesson %>
            <%= link_to "Just take a look", lesson_classroom_path(@course.classrooms.first, lesson_id: @course.classrooms.first.first_lesson(current_user)), class: "btn btn-sm btn-default" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>