config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations, :controllers => {
    omniauth_callbacks: "omniauth_callbacks",
    passwords: "passwords",
    confirmations: "confirmations",
    sessions: "sessions"
  }

  devise_scope :user do
    resource :registration,
      only: [:new, :create],
      path: 'users',
      controller: 'registrations',
      as: :user_registration
  end

  get "users/edit_profile" => "users#edit_profile", as: :edit_profile
  post "users/update_profile" => "users#update_profile", as: :update_profile
  post "users/:id/add_user_role" => "users#add_user_role", as: :add_user_role
  post "users/:id/remove_user_role" => "users#remove_user_role", as: :remove_user_role

  resources :users, only: [:index, :show, :destroy] do
    collection do
      get 'inactive'
    end
  end

  resources :courses do
    member do
      get 'edit_structure'
      post 'set_main'
      post 'unset_main'
    end
  end

  resources :sections do
    member do
      post 'move_down'
      post 'move_up'
    end
  end

  resources :lessons do
    member do
      post 'move_down'
      post 'move_up'
      post 'attach_task'
      post 'detach_task'
      post 'attach_quiz'
      post 'detach_quiz'
    end
  end

  resources :classrooms do
    member do
      get 'lesson/:lesson_id' => 'classrooms#lesson', as: :lesson
      get 'lesson/:lesson_id/task/:task_id' => 'classrooms#lesson_task', as: :lesson_task
      get 'lesson/:lesson_id/task/:task_id/solution' => 'classrooms#task_solution', as: :task_solution
      get 'lesson/:lesson_id/task/:task_id/successful_runs' => 'classrooms#task_successful_runs', as: :task_successful_runs
      get 'lesson/:lesson_id/task/:task_id/task_runs' => 'classrooms#task_runs', as: :task_runs
      get 'lesson/:lesson_id/task/:task_id/task_run/:task_run_id' => 'classrooms#task_run', as: :task_run
      get 'lesson/:lesson_id/task/:task_id/student_task_runs' => 'classrooms#student_task_runs', as: :student_task_runs
      post 'lesson/:lesson_id/task/:task_id/solve' => 'classrooms#solve_task', as: :solve_task

      get 'lesson/:lesson_id/quiz/:quiz_id' => 'classrooms#lesson_quiz', as: :lesson_quiz
      get 'lesson/:lesson_id/quiz/:quiz_id/attempt' => 'classrooms#attempt_quiz', as: :attempt_quiz
      get 'lesson/:lesson_id/quiz/:quiz_id/attempt/:quiz_attempt_id' => 'classrooms#show_quiz_attempt', as: :show_quiz_attempt
      get 'lesson/:lesson_id/quiz/:quiz_id/student_quiz_attempts' => 'classrooms#student_quiz_attempts', as: :student_quiz_attempts
      get 'lesson/:lesson_id/quiz/:quiz_id/student_quiz_attempt' => 'classrooms#student_quiz_attempt', as: :student_quiz_attempt
      post 'lesson/:lesson_id/quiz/:quiz_id/submit' => 'classrooms#submit_quiz', as: :submit_quiz

      get 'users'
      get 'progress'
      get 'student_progress'
      post 'enroll'
      post 'remove_user'
      post 'update_user_limit'
      post 'add_waiting'
      post 'activate_user'
    end
  end

  resources :tasks do
    member do
      get 'solve'
      get 'runs'
      get 'runs_limits'
      get 'solution'
      post 'do_solve'
      post 'update_checker'
      post 'update_runs_limit'
      post 'resubmit_run'
    end

    collection do
      get 'all_runs'
      get 'stats'
    end
  end

  resources :quizzes do
    member do
      get 'attempt'
      get 'show_attempt'
      post 'submit'
    end

    collection do
      get 'all_attempts'
    end
  end

  resources :user_invitations, only: [:index, :create, :update, :destroy]

  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'about_codemarathon' => 'pages#about_codemarathon', as: :about_codemarathon

  root 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="margin-top-small">
      <span class="text-muted">CodeMarathon 2015</span>
      <span class="glyphicon glyphicon-option-vertical"></span>
      <%= link_to 'About', about_path %>
      <span class="glyphicon glyphicon-option-vertical"></span>
      <%= link_to 'Contact', contact_path %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <% if classroom_mode? %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
    <% end %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag('hiredintech_logo.png') %>
    <% end %>
  </div>
  <!-- /.navbar-header -->
  <ul class="nav navbar-top-links navbar-right">
    <% if user_signed_in? %>
      <% if current_user.has_role?(User::ROLE_ADMIN) %>
        <li><%= link_to "Manage users", users_path, class: "main-item" %></li>
      <% end %>

      <% if current_user.has_role?(User::ROLE_TEACHER) %>
        <li><%= link_to "Start new course", new_course_path, class: "main-item" %></li>

        <%= render partial: 'layouts/tasks_header_item' %>
        <%= render partial: 'layouts/quizzes_header_item' %>
      <% end %>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle main-item" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= truncate(current_user.display_name, length: 25) %> <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Edit profile', edit_profile_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    <% else %>
      <li class="sign-in-item"><%= link_to 'Log in', new_user_session_path, class: "main-item" %></li>
      <li><%= link_to 'Sign up', new_user_registration_path, class: "main-item" %></li>
    <% end %>
    <li><%= link_to 'About', about_path, class: "main-item" %></li>
  </ul>

  <% if classroom_mode? %>
    <%= render partial: 'courses/menu_new', locals: { course: @classroom.course, current_lesson: @lesson } %>
  <% end %>
</nav>

app/views/layouts/_quizzes_header_item.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle main-item" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Quizzes<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Create quiz", new_quiz_path %></li>
    <li><%= link_to "Quiz list", quizzes_path %></li>
    <li><%= link_to "All attempts", all_attempts_quizzes_path %></li>
  </ul>
</li>

app/views/layouts/_tasks_header_item.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle main-item" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tasks<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Create task", new_task_path %></li>
    <li><%= link_to "Task list", tasks_path %></li>
    <li><%= link_to "All runs", all_runs_tasks_path %></li>
    <li><%= link_to "Statistics", stats_tasks_path %></li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HiredInTech's Training Camp for Coding Interviews</title>
  <%= Gon::Base.render_data %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "favicon.png", type: "image/png", rel: "icon" %>
  <%= favicon_link_tag "favicon.ico", type: "image/x-icon", rel: "shortcut icon" %>
</head>
<body>
  <div id="wrapper">

    <%= render partial: 'layouts/header' %>

    <div id="<%= classroom_mode? ? 'page-wrapper' : 'wide-container' %>">
      <% if notice.present? %>
        <p class="alert alert-success alert-dismissible alert-top" role="alert" >
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </p>
      <% end %>

      <% if alert.present? %>
        <p class="alert alert-danger alert-dismissible alert-top" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </p>
      <% end %>

      <%= yield %>
    </div>

    <%= render partial: 'layouts/footer' %>

  </div>
</body>
</html>